#!/bin/sh

# OLD using gcc
#echo g++ -g -o finddup finddup.cpp -lssl
#g++ -g -o finddup finddup.cpp -lssl

# We now use clang
compiler=clang++
exe=finddup
src=finddup.cpp
libpaths=$(pkg-config --libs --cflags libssl)
#flags='-g -std=c++11'
flags='-O2 -std=c++11'
echo ${compiler} ${flags} -o ${exe} ${src} ${libpaths}
${compiler} ${flags} -o ${exe} ${src} ${libpaths}
